quarkus.flyway.migrate-at-start=true
quarkus.hibernate-orm.database.generation=validate
quarkus.http.port=8081

# Kafka producer for payment confirmation events
kafka.bootstrap.servers=localhost:9092
mp.messaging.outgoing.pagamentos-confirmados.connector=smallrye-kafka
mp.messaging.outgoing.pagamentos-confirmados.topic=pagamentosConfirmados
mp.messaging.outgoing.pagamentos-confirmados.value.serializer=org.apache.kafka.common.serialization.StringSerializer
